on:
  workflow_dispatch:
  repository_dispatch:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy"
  cancel-in-progress: true
  #ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup GitHub Pages
      id: pages
      uses: actions/configure-pages@v1
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.18.1
    - name: Install dependencies and build site
      run: |
        sed -i 's/--port \$PORT/--port 3000/g' package.json
        npm install --prefer-offline --no-audit --legacy-peer-deps
        npm install scratch-vm@git+https://huggingface.co/datasets/soiz1/s4s-vm
        export NODE_ENV=production
        NODE_OPTIONS=--openssl-legacy-provider npx webpack --config webpack.config.js

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build/

  deploy:
    environment:
      name: github-pages
      url: 'https://penguinmod.com/project'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
