/* generated by pull.js */
const manifest = {
  "name": "Save project to Google drive",
  "description": " \"Googleに保存\" を追加し、Googleドライブに保存するようにします。",
  "tags": [
    "recommended"
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "enabledByDefault": true
};
import {mediaRecorderSupported} from "../../environment";
if (!mediaRecorderSupported) manifest.unsupported = true;
export default manifest;